scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.32
    max_x:  0.32
    min_y: -0.32
    max_y:  0.32
    min_z: -0.2
    max_z:  0.2